github:
  organization: giantswarm
  repositories:
    - name: giantswarm
      leader: true
    - name: roadmap

rules:
  - description: Include area/...
    mode: include
    pattern: area/.*

  - description: Include component/...
    mode: include
    pattern: component/.*

  - description: Include effort/...
    mode: include
    pattern: effort/.*

  - description: Include enablement/...
    mode: include
    pattern: enablement/.*

  - description: Include impact/...
    mode: include
    pattern: impact/.*

  - description: Include needs/...
    mode: include
    pattern: needs/.*

  - description: Include provider/...
    mode: include
    pattern: provider/.*

  - description: Include team/...
    mode: include
    pattern: team/.*

  - description: Include topic/...
    mode: include
    pattern: topic/.*

  - description: Include ui/...
    mode: include
    pattern: ui/.*

  - description: Include ux/...
    mode: include
    pattern: ux/.*

